alias :q='cowsay -d "this isn'\''t Vim"'
alias :w='cowsay -b "this isn'\''t Vim"'
alias aliases='vim ~/.bash_aliases && source ~/.bash_aliases'
alias diff2='diff --color=always -y'
alias dir='dir --color=auto'
alias grep='grep --color=auto -i'
alias la='ls -A'
alias ll='ls -l -h'
alias lla='ll -A'
alias ls='ls --color=auto'
alias miola='cowsay -e ^^ "te extraño, mi galletita"'
alias miola2='cowsay -e ^^ "🌊Nandita 💃 bonita 🌊"'
